install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Modulo.Collect.Service.VS2010.sln

artifacts:
  - path: '**\Modulo.Collect.Service.msi'
    name: modSicInstaller